# Generated by Django 2.2 on 2021-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users_who_join',
            field=models.ManyToManyField(related_name='join_trip', to='main.User'),
        ),
    ]
